
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
#      routes[0]:
#        id : post
#        uri: lb://memorizing-core
#        predicates[0]: Path=/
#        predicates[1]: Method=GET
#      routes[1]:
#        id: get
#        uri: lb://memorizing-core
#        predicates[0]: Path=/
#        predicates[1]: Method=POST

eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.76:8761/eureka
